development:
  adapter: postgresql
  encoding: unicode
  database: lifekeep_development
  pool: 5
  username: postgres
  password: 'P0stgres'
  host: localhost
  port: 5432

test:
  adapter: postgresql
  encoding: unicode
  database: lifekeep_test
  pool: 5
  username: postgres
  password: 'P0stgres'
  host: localhost
  port: 5432

production:
  adapter: postgresql
  encoding: unicode
  database: lifekeep_production
  pool: 5
  username: postgres
  password: 'P0stgres'
  host: localhost
  port: 5432